- name: Configurar identidade do Git
  run: |
    git config --global user.name "github-actions[bot]"
    git config --global user.email "github-actions[bot]@users.noreply.github.com"

- name: Publicar com Auto
  run: yarn auto shipit --base-branch=main
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
